### ISSUE TITLE
The extension loses the provided credentials upon BurpSuite reboot.

### ISSUE THREAD

**Issue by m0pam** [codewatchorg/Burp-AnonymousCloud#1]
Hi there, upon closing and reopening BurpSuite, the extensions are removed, this is extremely annoying and pretty much make the extensions unusable on a daily basis.

Would it be possible to add a configuration file from which the extension loads the credentials upon burpsuite boot?

**Comment by codewatchorg** [comment]
I just submitted a pull request to PortSwigger that addresses this issue: https://github.com/PortSwigger/anonymous-cloud/pull/2.

You can use the JAR in this GitHub in the interim as it now supports saving credentials to disk.
